### ISSUE TITLE
Monster Loot Compendium

### ISSUE THREAD

**Issue by ctbritt** [MaxPat931/Macros#1]
hi! I see you have a monster loot macro, but where did you find a compendium of Monster Loot? I've got the PDF from DMs Guild, but not sure how I would go about converting it to a Foundry compendium. Any thoughts?

**Comment by action-jay** [comment]
Hiya!

For Monster Loot, I recreated each item in Foundry, put those in rollable tables for each creature, then set up a Gatherer journal entry for each of those tables. It was a bit of work! Since the book is paid content, I couldn't share the resulting compendiums publicly.

I started the same process for the free alternative "Creature Loot", but haven't been to work entering data for a while, since I've been pretty busy running campaigns for my group. You can still check it out to see how it's structured though! https://github.com/action-jay/creature-loot

**Comment by MaxPat931** [comment]
Yea, so my macro looks to the compendium identified on line 13 for an item named "[Targeted Actor] Harvest" (e.g. Goblin Harvest) It uses the Actor name, not the Token name
I did make the compendium and items myself, so I cant really recommend it because it's a lot of manual work haha
I initially kicked this project off because of this reddit post https://www.reddit.com/r/FoundryVTT/comments/slevzw/macro_monster_harvest_reference/ which has some basic guidance on how to rip out the contents of the PDF into a more manageable format, but it's a pretty tedious process
Ultimately the way that I did it was to have 3 compendiums:
Monster Loot - This contains the individual lootable items, e.g. Dragon Tooth, Dragon Scale, etc
Craftables - This contains the items that can be crafted with those items, e.g. Dragon Tooth Dagger, etc.
Harvest Items - This contains items representing all the Loot that can be gathered from a given creature, which is grabbed by the macro, e.g. [[1d4]] [Dragon Tooth], [[1d2]] [Dragon Scale], etc

ultimately, it should work like this https://imgur.com/a/8DBf315
